### ISSUE TITLE
Make better with updated_at

### ISSUE THREAD

**Issue by ZerooCool** [yireo/mod_github_repos#1]
Hello, if you have the time, and, if you know how to ...
I would like to sort by last modified date with updated_at

<?php
/**
 * Joomla! component SimpleLists
 *
 * @author Yireo
 * @copyright Copyright 2013
 * @license GNU Public License
 * @link http://www.yireo.com/
 */

defined('_JEXEC') or die('Restricted access');
$count = $params->get('count', 10);
?>

<?php if(!empty($items)) : ?>
<ul>
<?php $i = 0; ?>
<?php foreach( $items as $item ) : ?>
    <?php if($i > $count) break; ?>
    <li>
        <a href="<?php echo $item['html_url']; ?>"><?php echo $item['full_name']; ?></a>
    </li>

<?php $i++; ?>
<?php endforeach; ?>
</ul>
<?php endif; ?>

**Comment by yireo** [comment]
Thanks for opening the issue. Note that we are not offering this extension as a way for non-developers to get a free extension. Instead, this is a true open-source project: The source is open and available for sharing. But to customize things, you need to be (or become) a PHP developer.
